import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { gql, useQuery } from "@apollo/client";
import { Hero } from "../components/Hero";
import { Navbar } from "../components/Navbar";
import { Drawer } from "../components/Drawer";

const buttonItems = [
  {
    label: "O nas",
    href: "/o-nas",
  },
  {
    label: "Artyści",
    href: "/artysci",
  },
  {
    label: "Lokale",
    href: "/lokale",
  },
  {
    label: "Wydarzenia",
    href: "/wydarzenia",
  },
];

const queryPlaceNames = gql`
  query Posts {
    posts(where: { categoryName: "Lokale" }) {
      nodes {
        title
      }
    }
  }
`;

const Home: NextPage = () => {
  // const { data, loading, error } = useQuery(queryPlaceNames);
  // console.log(data);

  return (
    <>
      <Head>
        <title>Gizmo Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="drawer">
          <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
          <div className="flex flex-col drawer-content">
            <Navbar />
            <div className="">
              <div className="flex flex-col justify-center items-center">
                <Hero />
                {/* <div className="">
              {buttonItems.map((item) => (
                <Link key={item.label} href={item.href} passHref>
                  <button className="main-logo-btn" type="button">
                    <i className="fas fa-heart"></i> {item.label}
                  </button>
                </Link>
              ))}
            </div> */}
              </div>
            </div>
          </div>
          <Drawer />
        </div>
      </main>
    </>
  );
};

export default Home;
