import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { gql, useQuery } from "@apollo/client";
import { Hero } from "../components/Hero";
import { Navbar } from "../components/Navbar";
import { Drawer } from "../components/Drawer";
import { Footer } from "../components/Footer";
import { Featured } from "../components/Featured";

const queryPlaceNames = gql`
  query Posts {
    posts(where: { categoryName: "Artyści" }) {
      nodes {
        title
      }
    }
  }
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Gizmo Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="drawer">
          <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
          <div className="flex flex-col drawer-content">
            <Navbar />
            <Hero />
            <Featured />
            <Footer />
          </div>
          <Drawer />
        </div>
      </main>
    </>
  );
};

export default Home;
